# Generated by Django 3.2.5 on 2022-01-28 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overview', models.TextField(blank=True, null=True)),
                ('release_date', models.DateField()),
                ('popularity', models.CharField(max_length=200)),
                ('vote_average', models.DecimalField(decimal_places=1, max_digits=2)),
                ('vote_num', models.IntegerField()),
                ('title', models.CharField(max_length=500)),
                ('video', models.BooleanField(default=False)),
                ('movie_number', models.IntegerField()),
            ],
        ),
    ]
