# Generated by Django 3.2.5 on 2022-01-28 23:06

from django.db import migrations,models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='movie_number',
        ),
        migrations.AddField(
            model_name='movies',
            name='number',
            field=models.IntegerField(),
        ),
    ]
